### ISSUE TITLE
wishlist: add search limiting by network ranges (not just country)

### ISSUE THREAD

**Issue by aaronkaplan** [NettleSec/TriOp#1]
Just as limiting by country, it would be great to have the same feature just for network ranges and/or ASNs.
By default, shodan allows for searching by netblock range.

**Comment by NettleSec** [comment]
Parameterized searches have been added - searches can now be done using arbitrary filters ("net:", "as:", "country:", etc.). For more information, see https://untrustednetwork.net/en/2021/03/08/triop-update-version-1.1/.

**Comment by aaronkaplan** [comment]
Hey NettleSec,

Super thanks a lot!
Very practical :)
