### ISSUE TITLE
Results to output IPs searched

### ISSUE THREAD

**Issue by faustus25** [NettleSec/TriOp#2]
A feature request to return the IPs that have hits for ports, CVEs etc. in output and output file.

Would help identify any external systems that need to be remediated.

**Comment by NettleSec** [comment]
This feature would require a paid Shodan account and, unlike getting simple "counts", it would also cost query credits (see https://help.shodan.io/the-basics/credit-types-explained). The aim is for all TriOp functions to be usable with a free account.

If you do have a paid account and are willing to spend the credits, however, Shodan CLI (https://cli.shodan.io/) already has a function for getting a list of IPs that satisfy a specific query (shodan search --fields ip_str [search_terms]), so there is no need to use TriOp for this.
